import type { ProjectRecord } from "@/content/projects/types";

export const jacobMarinerProject: ProjectRecord = {
  slug: "jacob-mariner",
  clientName: "Jacob Mariner",
  clientState: "create",
  shortTransformation: "A recruiting website became a living athlete intelligence system.",
  client: "Jacob Mariner is a Class of 2028 student-athlete at Long Island Lutheran, competing in basketball with LuHi and Heat Elite and in track and field with LuHi. His public profile identifies the 6′0″ combo-guard listing as BluPrint Hoops roster information and the 4.0 GPA as self-reported.",
  situation: "A young athlete’s digital presence changes every time he competes. Film, event posts, team recognition, roster information, track databases, academic context, and recruiting pathways were distributed across sources with different levels of authority. A static portfolio would begin aging as soon as it launched.",
  objective: "Create one recruiting-first profile that could present the athlete clearly now, preserve where each public claim came from, and accept new evidence over time without blending verified records, publisher statements, athlete-supplied information, and context into one unsupported story.",
  strategy: [
    "Treat the athlete profile as an evolving record rather than a fixed collection of promotional pages.",
    "Lead with film and recruiting context while keeping supporting evidence close enough to inspect.",
    "Classify public information by its publisher and verification source instead of presenting every claim with equal authority.",
    "Design the content structure to absorb new seasons, events, performance records, recognition, and recruiting pathways without rebuilding the experience.",
  ],
  experience: [
    "A recruiting-first opening establishes school, program, position, height, class year, and immediate contact paths.",
    "Featured film, current game evidence, athlete profile, performance, academics, and inquiries form one deliberate hierarchy.",
    "Source language remains visible at the point of use so a recruiter can understand what is published, verified, or self-reported.",
    "Desktop, tablet, mobile, and social-entry compositions preserve the same record through independent responsive choreography.",
  ],
  systems: [
    "A structured athlete record keeps identity, basketball, track and field, academics, film, recognition, and contact pathways connected.",
    "Evidence records associate a claim with its publisher, date, source URL, media, and verification class.",
    "A film hierarchy separates featured edits, camp media, and current source-posted game action.",
    "Recruiting, media, general, and partnership paths move attention toward an adult-managed next step.",
  ],
  transformation: "The athlete’s public presence moved from a set of scattered posts and records to one evolving, source-aware recruiting environment.",
  liveUrl: "https://www.jacobmariner.com/",
  visualIdentity: {
    primary: "#d0202c",
    secondary: "#090c0d",
    surface: "#f3f1ec",
    surfaceStrong: "#ddd9d0",
    text: "#0a0d0e",
    textMuted: "#5e605e",
    signal: "#ef3340",
    border: "#b9b7b0",
  },
  experienceProfile: {
    id: "jacob-athlete-intelligence",
    displayFamily: "sans",
    displayWeight: 720,
    displayTracking: "-0.065em",
    sectionSpacing: "clamp(5.5rem, 10vw, 10rem)",
    surfaceRadius: "0rem",
    ctaShape: "square",
    imageScale: "dominant",
    transitionDuration: "520ms",
    takeoverIntensity: 1,
  },
  media: {
    card: {
      src: "/case-studies/jacob-mariner/card.jpg",
      alt: "Jacob Mariner recruiting profile opening with his name, LuHi and Heat Elite context, and film and recruiting pathways.",
      width: 1200,
      height: 750,
    },
    desktop: {
      src: "/case-studies/jacob-mariner/live-desktop.jpg",
      alt: "Jacob Mariner desktop recruiting experience showing his athlete identity, current program context, and direct film and recruiting paths.",
      width: 1440,
      height: 900,
    },
    tablet: {
      src: "/case-studies/jacob-mariner/live-tablet.jpg",
      alt: "Jacob Mariner tablet recruiting experience with athlete identity, film navigation, and contact pathways composed for an intermediate viewport.",
      width: 768,
      height: 1024,
    },
    mobile: {
      src: "/case-studies/jacob-mariner/live-mobile.jpg",
      alt: "Jacob Mariner mobile recruiting experience with his identity, current program context, film actions, and recruiting contact visible in one opening view.",
      width: 390,
      height: 844,
    },
  },
  metadata: {
    title: "Jacob Mariner Athlete Intelligence Platform",
    description: "See how Mariner Nexus organized Jacob Mariner’s film, performance evidence, academics, athletic history, provenance, and recruiting pathways into one evolving athlete intelligence platform.",
    ogImage: "/og/jacob-mariner",
  },
  presentation: {
    recordNumber: "06",
    taxonomy: "Athlete Intelligence · Recruiting · Evidence",
    heroSummary: "A Class of 2028 athlete required more than a personal site. The platform had to organize film, performance evidence, athletic history, academics, recruiting context, and new information as his career continues to develop.",
    heroCta: "Visit JacobMariner.com",
    situationHeading: "A young athlete’s digital presence changes every time he competes.",
    objectiveHeading: "Build a profile that can keep becoming more useful.",
    strategyHeading: "Design the evidence model before arranging the highlights.",
    experienceHeading: "The athlete, the film, and the record become one experience.",
    experienceIntro: "The live product makes recruiting context immediate while keeping film, published performance, track evidence, academics, provenance, and contact pathways available for deeper inspection.",
    systemsHeading: "The interface is backed by a source-aware record.",
    systemsIntro: "The useful system is not an autonomous scouting engine. It is a structured way to preserve context, connect evidence, and keep a changing athlete profile legible to the humans using it.",
    liveCta: "Visit JacobMariner.com",
    roles: ["Strategy", "Athlete experience architecture", "Evidence and provenance model", "Content system", "Responsive web engineering"],
    journey: ["Identity", "Film", "Evidence", "Athletic record", "Recruiting pathways"],
  },
  intelligenceRecord: {
    challengeHeading: "The source is part of the story.",
    challenge: "Athlete information arrives through channels that were created for different purposes. Instagram posts, team announcements, tournament content, game film, event graphics, school rosters, track databases, recruiting conversations, academic information, and future statistics cannot responsibly be flattened into one undifferentiated profile.",
    fragmentedSources: ["Instagram posts", "Team announcements", "Tournament content", "Game film", "Event graphics", "School rosters", "Track databases", "Recruiting conversations", "Academic information", "Future statistics"],
    verificationClasses: ["Verified fact", "Athlete-published", "Team-published", "Third-party verified", "Contextual", "Unsupported inference"],
    architectureHeading: "Information becomes useful when its context survives the journey.",
    architectureIntro: "The current experience already organizes sources, evidence, the athlete record, and recruiting pathways. The final layer is an explicitly labeled future architecture—not a claim about what is operating today.",
    architectureLayers: [
      { name: "Source layer", state: "operating", summary: "Information enters from distinct public publishers and formats.", items: ["Instagram", "Team records", "Tournament records", "Athletic.net", "MileSplit", "School athletics", "Game film", "Media"] },
      { name: "Evidence layer", state: "operating", summary: "Every usable claim retains enough context to inspect.", items: ["Source URL", "Publisher", "Date", "Claim", "Verification class", "Media", "Context"] },
      { name: "Athlete intelligence record", state: "operating", summary: "The evolving profile connects evidence without erasing its provenance.", items: ["Identity", "Basketball", "Track & field", "Academics", "Film", "Performance", "Programs", "Recognition", "Recruiting context"] },
      { name: "Experience layer", state: "operating", summary: "The record becomes a clear recruiting and social experience.", items: ["Recruiting profile", "Social profile", "Film", "Athlete snapshot", "Current run", "Contact pathways"] },
      { name: "Future intelligence", state: "future", summary: "Potential assistance remains separate from current product claims.", items: ["Automated ingestion", "Source monitoring", "Evidence validation", "Longitudinal performance", "Recruiter intelligence", "Notifications"] },
    ],
    provenanceHeading: "The system does not treat every claim equally.",
    provenanceIntro: "Published performance, team records, verified databases, athlete-supplied information, and contextual evidence are identified according to their source rather than blended into an unsupported profile.",
    evidence: [
      { label: "Current game evidence", value: "6 made threes · 55–54 published result · 2–1 weekend record · a steal, a block, and the game-winning assist", sourceClass: "Athlete-published · caption facts", sourceDate: { label: "Published Jul 12, 2026", dateTime: "2026-07-12" }, sourceLabel: "Inspect original game post", sourceUrl: "https://www.instagram.com/p/DatWd2SPjQj/" },
      { label: "Game recognition", value: "11 points vs. Nazareth · LuHi Players of the Game graphic", sourceClass: "Team-published", sourceDate: { label: "Verified Sep 11, 2026", dateTime: "2026-09-11" }, sourceLabel: "Open the published graphic", sourceUrl: "https://www.jacobmariner.com/media/images/luhi-players-of-game.jpeg" },
      { label: "Position and height", value: "Combo guard · 6′0″", sourceClass: "Roster-published", sourceDate: { label: "Summer 2026 roster · verified Sep 11, 2026", dateTime: "2026-09-11" }, sourceLabel: "Inspect BluPrint roster", sourceUrl: "https://www.instagram.com/p/DYSPQg8xJNI/" },
      { label: "Track and field", value: "400m 56.75 — May 7, 2026 season best · 56.62 — May 15, 2025 career best · 800m 2:10.36 — May 20, 2026 documented personal best", sourceClass: "Third-party verified", sourceDate: { label: "Source records checked Sep 11, 2026", dateTime: "2026-09-11" }, sourceLabel: "View Athletic.net record", sourceUrl: "https://www.athletic.net/athlete/28521345/track-and-field/all" },
      { label: "Track record cross-check", value: "Jacob Mariner athlete result history", sourceClass: "Third-party verified · MileSplit", sourceDate: { label: "Verified Sep 11, 2026", dateTime: "2026-09-11" }, sourceLabel: "View MileSplit record", sourceUrl: "https://ny.milesplit.com/athletes/18216870-jacob-mariner" },
      { label: "School track roster", value: "Long Island Lutheran track and field", sourceClass: "School-published", sourceDate: { label: "Verified Sep 11, 2026", dateTime: "2026-09-11" }, sourceLabel: "View LuHi Athletics roster", sourceUrl: "https://luhiathletics.org/sports/track-field/roster/jacob-mariner/812" },
      { label: "Academics", value: "4.0 GPA", sourceClass: "Self-reported", sourceDate: { label: "Observed Sep 11, 2026", dateTime: "2026-09-11" }, sourceLabel: "View athlete profile", sourceUrl: "https://www.instagram.com/jm_the_general/" },
    ],
    traditionalWebsite: ["Bio", "Photos", "Highlights", "Contact"],
    intelligencePlatform: ["Structured identity", "Source-backed claims", "Film hierarchy", "Performance ledger", "Cross-sport athletic evidence", "Academic context", "Recruiting pathways", "Provenance", "Continuous updates", "Future ingestion architecture"],
    operatingNow: ["Recruiting-first experience", "Film hierarchy", "Current game evidence", "Source attribution", "Athlete profile", "Track and field evidence", "Academic positioning", "Performance records", "Recruiting contact", "Media contact", "Partnership pathway", "Responsive social landing experience"],
    futureState: ["Automated source ingestion", "New evidence detection", "Confidence classification", "Duplicate detection", "Longitudinal stat ledger", "Coach and recruiter intelligence views", "Recruiting interaction history", "Notifications", "Source discrepancy detection"],
    media: {
      film: { src: "/case-studies/jacob-mariner/film-experience.jpg", alt: "Jacob Mariner film experience with a featured MADE Hoops cut, supporting reels, and original source context.", width: 1440, height: 900 },
      provenance: { src: "/case-studies/jacob-mariner/provenance-evidence.jpg", alt: "Jacob Mariner current Heat Elite run showing source-posted game cuts and an explicit no-inferred-statistics statement.", width: 1440, height: 960 },
      performance: { src: "/case-studies/jacob-mariner/performance-record.jpg", alt: "Jacob Mariner performance record showing 11 points and team-published LuHi Players of the Game recognition.", width: 1440, height: 815 },
    },
  },
  publicationStatus: "published",
};
