import type { ProjectRecord } from "@/content/projects/types";

export const unduguProject: ProjectRecord = {
  slug: "undugu",
  clientName: "Undugu",
  clientState: "transform",
  shortTransformation: "From no meaningful digital presence to a credible, connected organizational platform.",
  client: "Undugu is a 501(c)(3) nonprofit organization focused on brotherhood, community, movement and participation. Its work includes gatherings, programs, community stories, and public ways to participate and support the mission.",
  situation: "Undugu had an established nonprofit mission, brotherhood, events, programs, and growing activity, but no meaningful digital presence capable of representing the organization publicly. Undugu needed a digital presence capable of supporting the credibility, participation, programs, events and public-facing needs of a 501(c)(3) nonprofit organization.",
  objective: "Translate the mission-driven nonprofit organization into a credible and useful digital presence that could support public understanding, organizational legitimacy, programs, events, participation, resources, communications, and future growth.",
  strategy: [
    "Begin with the organization and its real-world activity rather than a predetermined page template.",
    "Establish a clear information hierarchy for the movement, events, programs, impact, and ways to participate.",
    "Turn recurring activity into repeatable content pathways that can expand as the organization grows.",
    "Create clear audience journeys for understanding the mission, entering the community, attending events, and supporting the work.",
  ],
  experience: [
    "A distinctive Undugu identity leads the experience without losing clarity or usability.",
    "Organizational storytelling connects the mission to real gatherings, voices, and visible community activity.",
    "Navigation and calls to action create direct paths into events, programs, connection, and support.",
    "Desktop and mobile presentations preserve the same message through composition designed for each viewport.",
  ],
  systems: [
    "Structured event and program content creates repeatable public information pathways.",
    "External registration and donation actions connect interested visitors to the next operational step.",
    "Reusable content structure supports movement stories, impact information, resources, and future expansion.",
    "Clear communication pathways help the website remain useful even as Undugu's activity changes over time.",
  ],
  transformation: "Undugu moved from having no meaningful digital presence to presenting itself online as a credible, organized, functioning 501(c)(3) nonprofit organization.",
  liveUrl: "https://www.undugu.org/",
  visualIdentity: {
    primary: "#563372",
    secondary: "#281b34",
    surface: "#f6f2f8",
    surfaceStrong: "#e8deed",
    text: "#211827",
    textMuted: "#665c6b",
    signal: "#765392",
    border: "#c8b8d0",
  },
  experienceProfile: {
    id: "undugu-community-expression",
    displayFamily: "serif",
    displayWeight: 600,
    displayTracking: "-0.035em",
    sectionSpacing: "clamp(6rem, 12vw, 12rem)",
    surfaceRadius: "clamp(1.5rem, 4vw, 4rem)",
    ctaShape: "pill",
    imageScale: "dominant",
    transitionDuration: "700ms",
    takeoverIntensity: 1,
  },
  media: {
    card: { src: "/case-studies/undugu/card.webp", alt: "Undugu website opening showing its identity, brotherhood gathering, and movement message.", width: 1200, height: 750 },
    desktop: { src: "/case-studies/undugu/live-desktop.webp", alt: "Undugu desktop website experience with movement navigation, a brotherhood gathering, and the message You have been carrying too much alone.", width: 1600, height: 1000 },
    tablet: { src: "/case-studies/undugu/responsive-tablet.webp", alt: "Undugu tablet experience with full movement navigation, an intermediate hero composition, stacked actions, and a brotherhood gathering.", width: 1018, height: 895 },
    mobile: { src: "/case-studies/undugu/live-mobile.webp", alt: "Undugu mobile website experience with movement introduction, participation actions, and a brotherhood gathering.", width: 900, height: 1400 },
  },
  metadata: {
    title: "Undugu Transformation Record",
    description: "See how Mariner Nexus translated Undugu's 501(c)(3) nonprofit mission, brotherhood, programs, events, and participation into a credible connected digital presence.",
    ogImage: "/case-studies/undugu/og.webp",
  },
  presentation: {
    recordNumber: "01",
    situationHeading: "A mission-driven nonprofit needed a credible public presence.",
    objectiveHeading: "Translate the 501(c)(3) organization into a useful public platform.",
    strategyHeading: "Understand the nonprofit organization before designing pages.",
    experienceHeading: "The nonprofit organization becomes visible.",
    experienceIntro: "Undugu’s identity, message, real gatherings, and ways to participate come together as one clear public experience.",
    systemsHeading: "The experience leads somewhere useful.",
    systemsIntro: "The website organizes public information and connects attention to real participation pathways.",
    liveCta: "Experience Undugu Live",
    roles: ["Strategy", "Digital experience", "Information architecture", "Responsive web engineering"],
    journey: ["Recognition", "Organization", "Participation", "Support"],
  },
  publicationStatus: "published",
};
