import type { Metadata } from "next";
import { RouteFoundation } from "@/components/foundation/RouteFoundation";
import { createMetadata } from "@/lib/seo";

export const metadata: Metadata = createMetadata({ title: "Privacy", description: "Privacy information for the Mariner Nexus website and project inquiry process.", path: "/privacy" });

export default function PrivacyPage() {
  return <RouteFoundation eyebrow="Legal" title="Privacy" description="Mariner Nexus limits website and inquiry information to what is useful for responding, operating the site, and understanding its performance." note="This V1 notice applies to website and inquiry use. Client engagement data and contractual obligations are governed separately."><div className="mn-legal-copy"><h2>Website information</h2><p>Standard technical information may be processed for security, reliability, abuse prevention, and aggregate performance measurement.</p><h2>Project inquiries</h2><p>Information submitted through an inquiry is validated on the server and stored in the Mariner Nexus Google Workspace so it can be evaluated and answered. A notification email may be sent to the responsible Mariner Nexus inbox; the structured Workspace record remains the source of truth.</p><p>Inquiry information is used to begin and manage the requested project conversation. It is not sold, used to enroll you in a mailing list, or treated as consent to unsolicited marketing.</p><h2>Service providers</h2><p>Google Workspace processes the structured record. Resend may process a bounded notification email when notifications are enabled. Technical event measurement excludes names, contact details, and free-form inquiry responses.</p><h2>Questions</h2><p>Email <a href="mailto:info@marinernexus.com">info@marinernexus.com</a> with privacy questions or requests.</p></div></RouteFoundation>;
}
