import type { Metadata } from "next";
import { Container } from "@/components/foundation/Container";
import { Grid } from "@/components/foundation/Grid";
import { createMetadata } from "@/lib/seo";

export const metadata: Metadata = createMetadata({ title: "Start a Project", description: "Tell Mariner Nexus what you are trying to create, change, or connect.", path: "/start" });

export default function StartPage() {
  return <div className="mn-start-page mn-environment-light">
    <section className="mn-page-intro"><Container><Grid><div><div className="mn-signal-line" /><p className="mn-kicker">Start a Project</p><h1>Bring us the objective.</h1></div><div><p>You do not need the solution figured out. Tell us what you are trying to create, change, or make work together.</p><p>We will help determine what needs to exist around it.</p></div></Grid></Container></section>
    <section className="mn-inquiry-section"><Container><Grid><aside><p className="mn-kicker">Project inquiry</p><p>This presentation captures the right conversation without asking you to choose a package or technical service.</p><a href="mailto:hello@marinernexus.com">Prefer email? hello@marinernexus.com</a></aside><div className="mn-inquiry-form"><div className="mn-field"><label htmlFor="objective">What are you trying to create or change?</label><textarea id="objective" name="objective" rows={5} /></div><fieldset><legend>Where are you today?</legend><label><input name="current-state" type="radio" value="new" /> Starting something new</label><label><input name="current-state" type="radio" value="evolve" /> Have something that needs to evolve</label><label><input name="current-state" type="radio" value="connect" /> Need different pieces to work together</label><label><input name="current-state" type="radio" value="unsure" /> Not sure yet</label></fieldset><div className="mn-field"><label htmlFor="success">What does success look like?</label><textarea id="success" name="success" rows={4} /></div><div className="mn-field"><label htmlFor="current-presence">What exists today?</label><input id="current-presence" name="current-presence" placeholder="Optional current website" type="url" /></div><div className="mn-field"><label htmlFor="references">Is there anything you have seen that reflects the level you are looking for?</label><textarea id="references" name="references" placeholder="Optional references" rows={3} /></div><div className="mn-field"><label htmlFor="timeline">When are you hoping to move?</label><input id="timeline" name="timeline" type="text" /></div><div className="mn-contact-fields"><div className="mn-field"><label htmlFor="name">Name</label><input autoComplete="name" id="name" name="name" type="text" /></div><div className="mn-field"><label htmlFor="organization">Organization</label><input autoComplete="organization" id="organization" name="organization" type="text" /></div><div className="mn-field"><label htmlFor="email">Email</label><input autoComplete="email" id="email" name="email" type="email" /></div><div className="mn-field"><label htmlFor="phone">Phone <span>(optional)</span></label><input autoComplete="tel" id="phone" name="phone" type="tel" /></div></div><div className="mn-inquiry-submit"><button disabled type="button">Submit project inquiry</button><p id="inquiry-status">Secure online submission will be enabled with the approved inquiry persistence phase. Email remains available now.</p></div></div></Grid></Container></section>
  </div>;
}
