import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import YAML from "yaml";

export const REGISTER_FILES = {
  truth: "truth-register.yaml",
  authorizations: "authorization-register.yaml",
  approvals: "approval-register.yaml",
  changes: "change-register.yaml",
  qa: "qa.yaml",
  integrations: "integrations.yaml",
};

async function readYaml(file) {
  return YAML.parse(await readFile(file, "utf8"));
}

export async function loadKernel(directory) {
  const project = await readYaml(path.join(directory, "project.yaml"));
  const entries = await Promise.all(
    Object.entries(REGISTER_FILES).map(async ([key, file]) => [key, await readYaml(path.join(directory, file))]),
  );
  return { project, ...Object.fromEntries(entries) };
}

export function stable(value) {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.keys(value).sort().map((key) => [key, stable(value[key])]));
  }
  return value;
}

export function serializeJson(kernel) {
  return `${JSON.stringify(stable(kernel), null, 2)}\n`;
}

export function serializeTypescript(kernel) {
  return `// Generated by tools/wds. Do not edit.\nexport const projectKernel = ${JSON.stringify(stable(kernel), null, 2)} as const;\nexport type ProjectKernelArtifact = typeof projectKernel;\n`;
}

export async function writeArtifacts(directory, kernel) {
  await writeFile(path.join(directory, "project.normalized.json"), serializeJson(kernel));
  await writeFile(path.join(directory, "project.generated.ts"), serializeTypescript(kernel));
}

export async function checkArtifacts(directory, kernel) {
  const expected = [serializeJson(kernel), serializeTypescript(kernel)];
  const actual = await Promise.all([
    readFile(path.join(directory, "project.normalized.json"), "utf8"),
    readFile(path.join(directory, "project.generated.ts"), "utf8"),
  ]);
  return expected.every((value, index) => value === actual[index]);
}
